apiVersion: kahu.io/v1
kind: Backup
metadata:
   name: backup-demo
spec:
   excludedResources: []
   includedNamespaces: [default]
   metadataLocation: nfs
   includedResources:
    - name:
      kind: Pod
      isRegex: true
   hook:
      resources:
      - name: kahu_hook1
        includedNamespaces: [default]
        excludedNamespaces: [test]
        includedResources:
        - name:
          kind: Pod
          isRegex: true
        pre:
         - exec:
            container: busybox
            command: 
            - /bin/sh
            - -c
            - ls -l && hostname
            timeout: 5m
            onError: Fail

      - name: kahu_hook2
        includedNamespaces: [default]
        excludedNamespaces: [test]
        includedResources:
        - name:
          kind: Pod
          isRegex: true
        post:
         - exec:
            container: busybox
            command: 
            - /bin/sh
            - -c
            - ls -l && hostname
            timeout: 5m
            onError: Fail
