apiVersion: kahu.io/v1
kind: Backup
metadata:
  name: backup-kahu-001
spec:
  includeNamespaces: [default]
  metadataLocation: nfs
  includeResources:
      - name: busybox
        kind: Pod
        isRegex: true