apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.124
    path: "/mnt/nfs_share"
  mountOptions:
    - nfsvers=4.2
