apiVersion: apps/v1
kind: Deployment
metadata:
  name: kahu-backup-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: backup
  template:
    metadata:
      labels:
        provider: backup
    spec:
      serviceAccountName: kahu
      containers:
        - image: docker.io/library/controllermanager:v0.1.0
          imagePullPolicy: IfNotPresent
          name: backup
          command: ["/usr/local/bin/controllermanager"]
          args:
          - --meta-address=kahu-nfs-provider.default.svc.cluster.local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    provisioner: kahu
  name: kahu-backup-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kahu-backup-clusterrole
subjects:
  - kind: ServiceAccount
    name: kahu
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    provisioner: kahu
  name: kahu-backup-clusterrole
rules:
  - apiGroups:
    - "kahu.io"
    resources:
      - backups
      - backups/status
      - restores
      - restores/status
      - backuplocations
      - providers
    verbs:
      - get
      - watch
      - list
      - patch
      - update
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - create
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    provisioner: kahu
  name: kahu-backup-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kahu-backup-role
subjects:
  - kind: ServiceAccount
    name: kahu
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kahu
  namespace: default
