apiVersion: kahu.io/v1
kind: Backup
metadata:
  name: backup-demo-err
spec:
  # includeResources:
  excludeResources: []
  includeNamespaces: [kube-system_#]
  metadataLocation: nfs
  includeResources:
    - name:
      kind: Deployment
      isRegex: true
    - name:
      kind: Pod
      isRegex: true
